package com.com.sky.downloader.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.it.testconapp.javabean.Meizi;
import com.it.testconapp.javabean.Note;
import com.it.testconapp.javabean.User;

import com.com.sky.downloader.greendao.MeiziDao;
import com.com.sky.downloader.greendao.NoteDao;
import com.com.sky.downloader.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig meiziDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MeiziDao meiziDao;
    private final NoteDao noteDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        meiziDaoConfig = daoConfigMap.get(MeiziDao.class).clone();
        meiziDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        meiziDao = new MeiziDao(meiziDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Meizi.class, meiziDao);
        registerDao(Note.class, noteDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        meiziDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public MeiziDao getMeiziDao() {
        return meiziDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
